### ISSUE TITLE
Impossible to update remote theme to a newer version when running locally

### ISSUE THREAD

**Issue by qwtel** [benbalter/jekyll-remote-theme#12]
There is no way of updating a remote theme to a newer version when running locally.

Things that did not work:
* Specifying the exact version via tag, e.g. `remote_theme: qwtel/hydejack@gem-7.4.1` will still use whatever version was used on the first run (this works on GitHub Pages though)
* Removing Gemfile, Gemfile.lock, deleting gems and re-installing

What did work:
* Creating a new jekyll folder

**Comment by benbalter** [comment]
@qwtel Can you explain how you're reproducing this? Do you restart the server after you change the config? Each time the server starts (or a build is started), it should use a new temporary folder, and when it completes, it should remove the temporary folder, making caching between builds theoretically impossible.

**Comment by qwtel** [comment]
I can't reproduce it 😢 

However, the problem persists in one local jekyll folder.
A fresh clone of the remote repository would fix it. 
I'll wait and see if I encounter this again.
