### ISSUE TITLE
Specifying explicit version as documented, fails to download the zip

### ISSUE THREAD

**Issue by dcrossleyau** [benbalter/jekyll-remote-theme#14]
The README explains to declare a certain version of the remote theme, then use `@vX.Y.Z`. However that encounters a 404 Not Found. Using no leading `v` does work okay.

**Comment by benbalter** [comment]
@dcrossleyau can you provide some more information? What theme are you trying to use? What tag are you trying to use? What are you putting in your config file? I just tested locally and was able to build with the following: `remote_theme: pages-themes/PrImeR@v0.5.0`

**Comment by dcrossleyau** [comment]
Using `remote_theme: Balancingrock/classic-jekyll-theme@v1.9.4` gets the 404, while `remote_theme: Balancingrock/classic-jekyll-theme@1.9.4` is okay.

I see the difference now. The release tags do not have the leading "v". The same with some others that i investigated, e.g. minimal-mistakes.

Solved. Thanks.
