### ISSUE TITLE
Theme updates not reflected on GitHub Pages

### ISSUE THREAD

**Issue by mmistakes** [benbalter/jekyll-remote-theme#16]
Not exactly sure what's at fault here, the plugin or some sort of caching on GitHub Pages.

I recently pushed some updates to my theme [Minimal Mistakes](https://github.com/mmistakes/minimal-mistakes), version 4.8.0. For whatever reason changes made to layouts like `default.html` aren't being applied to the pages hosted on GitHub Pages.

You can see this easily when comparing [these lines in `_layouts/default.html`](https://github.com/mmistakes/minimal-mistakes/blob/master/_layouts/default.html#L5-L10):

```html
<!--
  Minimal Mistakes Jekyll Theme 4.8.0 by Michael Rose
  Copyright 2017 Michael Rose - mademistakes.com | @mmistakes
  Free for personal and commercial use under the MIT license
  https://github.com/mmistakes/minimal-mistakes/blob/master/LICENSE.txt
-->
```

Against the page source on GH Pages:

```html
<!--
  Minimal Mistakes Jekyll Theme 4.7.0 by Michael Rose
  Copyright 2017 Michael Rose - mademistakes.com | @mmistakes
  Free for personal and commercial use under the MIT license
  https://github.com/mmistakes/minimal-mistakes/blob/master/LICENSE.txt
-->
```

It did the same thing when I pushed an update for version `4.7.1`, but wasn't a big deal since the layouts themself didn't change. This release they did though, which is breaking a few things.

Post content and assets all updated fine with the files on `master`.

Thoughts?

**Comment by mmistakes** [comment]
Does jekyll-remote-theme handle versioned theme files? If I'm reading [these lines correctly](https://github.com/benbalter/jekyll-remote-theme/blob/master/lib/jekyll-remote-theme/downloader.rb#L34-L36) seems like if the theme files have been downloaded already they aren't downloaded again... even if they've changed.

```ruby
def downloaded?
  @downloaded ||= theme_dir_exists? && !theme_dir_empty?
end
```

**Comment by DirtyF** [comment]
@mmistakes have you tried with the git ref `mmistakes/minimal-mistakes@4.8.0`?

**Comment by mmistakes** [comment]
@DirtyF I tried referencing the most recent commit thinking that might force it and it made no difference.

I will give the tag a try now and see if that works...

**Comment by mmistakes** [comment]
@DirtyF same results with `remote_theme: mmistakes/minimal-mistakes@4.8.0`.

The strange thing is it pulls new [CSS](https://mmistakes.github.io/minimal-mistakes/assets/css/main.css) and [JS](https://mmistakes.github.io/minimal-mistakes/assets/js/main.min.js) assets I bundle in with the theme, but `_layouts/default.html` it doesn't seem to want to touch. My last release I made some changes to other layouts and those updated, so not sure if there's something weird with default due to inheriting other layouts or what.

**Comment by benbalter** [comment]
@mmistakes does your content repo (the one using the theme) have a default layout? GitHub Pages does no additional caching. The plugin itself caches within a build process (e.g., when the watch flag is enabled), but otherwise, each build command should build the site anew (and in the case of GitHub Pages, is in a fresh container so caching should be impossible). There may be some caching on the CDN layer, but requesting the theme version should break it.

**Comment by mmistakes** [comment]
@benbalter Wow! I feel like a complete idiot. When I migrated my `/docs` folder to use the remote theme plugin I didn't get all the layouts.

Removing that straggler `_layouts/default.html` fixes the issue. Sorry for the trouble :-(

**Comment by mariomeissner** [comment]
I'm facing a similar issue, I forked the mmistakes theme and added some modifications to the _includes/head.html. What do I have to do to force Github Pages to pull these changes?

Serving locally will work, but when I look at my online page, the changes are obviously not there.
My repos are:
https://github.com/mariomeissner/mariomeissner.github.io
Do I have to change some version?

**Comment by mmistakes** [comment]
@mariomeissner Ah I see what you did. You need to push some sort of commit to <https://github.com/mariomeissner/mariomeissner.github.io> to force a rebuild. It will pull the updated theme files then.

You can do a blank commit if you don't have actual content updates to push.

```
git commit --allow-empty -m "Force rebuild of site"
```

**Comment by mariomeissner** [comment]
Ah, that makes total sense. Thank you so much! <3
Issue solved :D
