### ISSUE TITLE
GitHub Pages Dependencies Missing

### ISSUE THREAD

**Issue by cravend** [benbalter/jekyll-remote-theme#17]
Hi,

I'm trying to use the GitHub Pages gem to preview my Jekyll site locally. Jekyll Remote Theme is listed as a dependency of the gem. Whenever I try to build my site, I get the following error:

`  Dependency Error: Yikes! It looks like you don't have jekyll-remote-theme or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'Could not open library 'libcurl': The specified module could not be found. . Could not open library 'libcurl.dll': The specified module could not be found. . Could not open library 'libcurl.so.4': The specified module could not be found. . Could not open library 'libcurl.so.4.dll': The specified module could not be found. ' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/!`

I'm using Git Bash on Windows 10. I've tried manually listing this plugin in my Gemfile. I've also ran `gem install jekyll-remote-theme`, neither of which helped. I'm not sure if this is an issue with my system or with the gem, so assistance would be appreciated.

**Comment by benbalter** [comment]
Please try [these instructions](http://blog.cloud-mes.com/2014/08/19/how-to-install-gem-curb-in-windows/), which may resolve the issue. I believe you need to install cURL.

**Comment by cravend** [comment]
I'm not sure what I'm doing wrong, but running the above error just leaves my terminal processing. I've let it sit for >30min without it doing anything.

**Comment by mattconsto** [comment]
@benbalter while those instructions didn't work for me, the following did.

1. Install libcurl.dll, add to $PATH, and create a copy without the .dll extension.
2. Copy %System32%/ws2_32.dll to %System32%/ws2_32 (No .dll extension)

Then it worked fine. I'm running Windows 10 64bit with Cygwin.

It seems that the dependency list in either jekyll-remote-theme, or one of it's dependancies is missing libcurl.dll (With extension), and ws2_32.dll 9With extension). I did a recursive grep, but couldn't find either. I think this might be an issue elsewhere.

```
21:02:49 user@host /jekyll-remote-theme
$ grep -r "ws2_32" .
21:02:52 user@host /jekyll-remote-theme
$ grep -r "cygws2_32.dll" .
21:03:44 user@host /jekyll-remote-theme
$ grep -r "libcurl.dll" .
21:08:01 user@host /jekyll-remote-theme
$ grep -r "libcurl" .
```

**Comment by cravend** [comment]
@mattconsto's suggestion worked for me!

**Comment by winstonlin** [comment]
I ran into this problem and none of the above solutions worked for me except this one (needed a DLL that actually worked with FFI):
https://stackoverflow.com/a/44817511
