### ISSUE TITLE
Error: Peer certificate cannot be authenticated with given CA certificates

### ISSUE THREAD

**Issue by jengalas** [benbalter/jekyll-remote-theme#20]
I'm having the same issue referenced here: https://github.com/benbalter/jekyll-remote-theme/issues/9 on a Windows 10 64-bit system. Any ideas? Thank you!

**Comment by benbalter** [comment]
[Version 174](https://github.com/github/pages-gem/releases/tag/v174) of the Pages Gem makes the Jekyll Remote Theme dependency optional, and should resolve issues for Windows users trying to preview sites locally that don't use a remote theme. Those wanting to preview a theme locally will need to following the troubleshooting steps above to install cURL in their local environment.

**Comment by opensorceror** [comment]
I still have this issue with Version 175

**Comment by benbalter** [comment]
Version 0.3.0 uses Ruby's native Net:HTTP, instead of Typhoeus (Libcurl), which may alleviate this issue.
