### ISSUE TITLE
Build Warning: Layout 'home' requested in index.md does not exist.

### ISSUE THREAD

**Issue by cjqw** [benbalter/jekyll-remote-theme#21]
Hello, I tried to use this plugin to switch to monochrome theme,below is the related configuration:
```
plugins:
  - jekyll-remote-theme

remote_theme: dyutibarma/monochrome
```
but when I tried to build the site, jekyll print a warning and the generated index.html in _site folder is empty. Here is the output of jekyll build
```
WARN: Unresolved specs during Gem::Specification.reset:
      listen (~> 3.0)
      rouge (< 4, >= 1.7)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Configuration file: /home/qw/blog/cjqw.github.io/_config.yml
            Source: /home/qw/blog/cjqw.github.io
       Destination: /home/qw/blog/cjqw.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
      Remote Theme: Using theme dyutibarma/monochrome
     Build Warning: Layout 'home' requested in index.md does not exist.
                    done in 2.709 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
```
when I run jekyll serve everything seems well except the index page is blank.
I don't have much knowledge about jekyll, is this theme not gem-based or I should 
add something in my config?

**Comment by benbalter** [comment]
@cjqw  you must use one of the theme's provided layouts in https://github.com/dyutibarma/monochrome/tree/master/_layouts (which does not include a `home` layouts).
