### ISSUE TITLE
Feature request: Caching mechanism for remote theme

### ISSUE THREAD

**Issue by sahilarora535** [benbalter/jekyll-remote-theme#22]
I am not sure if this gem already has this feature or not, but with the current implementation, it takes a lot of time to build a website by downloading the entire theme. It would be great if we have some caching mechanism such that building the jekyll site using remote theme speeds up.

**Comment by benbalter** [comment]
@sahilarora535 the theme is cached between builds (e.g., with the `--watch` setting), but not between command invocations (e.g., `jekyll build`). Otherwise, we wouldn't know when to purge the cache.

**Comment by sahilarora535** [comment]
@benbalter This actually makes sense. However, it may also be useful to have some feature where the theme is cached between builds via the `jekyll build` command. For instance the `git config credential.helper "cache --timeout=18000"` sets the `git` password cache timeout to be 18000 secs because users don't really change passwords too often. Similarly, a user may execute and build the website tens of times every hour, and the theme may not have been changed a lot in that time. For such cases, a manual caching mechanism may help save a lot of time and bandwidth. WDYT?

**Comment by pixelastic** [comment]
I would be interested in a way to have a cache between `jekyll build` calls as well. 

I'm developing the `jekyll-algolia` plugin, and as part of my test suite I'm testing that my plugin plays well with other plugins. To do that I replicate a build of a common website, that is using `jekyll-remote-theme`. Each time I play the test, I have to re-download the theme, which adds considerable time to the tests.

If I could add a cache, even just one hour, it will make the process easier.
