### ISSUE TITLE
Theme updates not propagating to other GitHub Pages

### ISSUE THREAD

**Issue by raveious** [benbalter/jekyll-remote-theme#24]
So, I've been experimenting with the idea of keeping public resources and documents in public repos and using GitHub Pages to make them more accessible. I created a new theme repo to contain the formatting info and refer to the theme on the content repositories, but updates to the theme repo don't seem to be reflected on the other ones. The theme seems to be captured only when an update is made to the content repo. Is that expected or is there something else that I need to do in order to have it auto-update?

The theme repo doesn't really have releases, so I was hoping to just point it to the HEAD of the master branch to have it auto-update from that.

**Comment by benbalter** [comment]
> The theme seems to be captured only when an update is made to the content repo. Is that expected or is there something else that I need to do in order to have it auto-update?

Correct. GitHub Pages is a static site generator and we do not automatically rebuild all sites that depend on a given theme when that theme updates. You will need to rebuild each site when you want them rebuilt.

**Comment by raveious** [comment]
That's what I figured was going on, but just wanted to make sure.
