### ISSUE TITLE
Allow non-github remote themes to be specified

### ISSUE THREAD

**Issue by peacememories** [benbalter/jekyll-remote-theme#25]
It is nice to be able to specify a custom theme without having to add a git subrepo or similar, but not all of my projects can or want to have their themes hosted on Github.

It would be great to specify a `git` or `http` url (e.g. `git://gitlab.example.com/user/mytheme`).

Right now it is necessary for me to either embed the theme in my project, add it as a subrepo or add complexity to my build process by downloading the theme during build time.

Thanks for creating this very useful addon and thanks for considering this request :)

**Comment by benbalter** [comment]
Restricting to themes on GitHub.com was motivated by security concerns. Right now the clone process simply grabs and unzips the repository's archive (which GitHub creates). If we pointed to arbitrary zip files, we risk cloning and attempting to unzip malicious zips. If we wanted to expand to clone via Git (the original implementation) we add a lot of complexity which this approach was intended to simplify.
