### ISSUE TITLE
Gitlab repo support

### ISSUE THREAD

**Issue by mittalyashu** [benbalter/jekyll-remote-theme#33]
### Is your feature request related to a problem? Please describe the problem you're trying to solve.

Allow users to use a gitlab hosted remote theme

### Describe alternatives you've considered

created a connection between Github and GitLab repo and working directly on gitlab repo and the changes are automatically synced on Github repo.

**Comment by allejo** [comment]
See #25

**Comment by mittalyashu** [comment]
What kind of security issues are there with GitLab?

**Comment by mittalyashu** [comment]
> If we wanted to expand to clone via Git (the original implementation) we add a lot of complexity which this approach was intended to simplify.

So, no plans for adding GitLab
