### ISSUE TITLE
Theme extension / inheritance

### ISSUE THREAD

**Issue by mrmanc** [benbalter/jekyll-remote-theme#35]
### Is your feature request related to a problem? Please describe the problem you're trying to solve.

I’m interested to know the best way to host a tailored version of an existing theme. I would like to add some common style that is still hosted remotely so that it can be maintained in one place.

### Describe the solution you'd like

I’m wondering if it is possible / sensible to extend existing themes by chaining remote_theme calls. I don’t know enough about how Jekyll themes work to know if this is even plausible, let alone sensible. This way I could host a theme which referred to `mmistakes/minimal-mistakes` for example, and overrode or added certain layouts / styles.

### Describe alternatives you've considered

* Git submodules for the common style (feels like voodoo, and would only satisfy some of the requirements)
* Forking the theme (don’t like the idea of regularly merging changes)
* External stylesheet (satisfies the common style, but not the extra / overridden layouts etc)

**Comment by nickgarlis** [comment]
@benbalter how are you thinking of addressing this issue ? This seems sounds very useful. I would like to help.

**Comment by benbalter** [comment]
Originally I had thought of plugin reading the remote theme's Gemspec and requiring any themes listed as dependencies there. I think the better path forward to be parent/child theme support in Jekyll core (for Gem-based themes), off which this plugin can build.

**Comment by mama805** [comment]
> Originally I had thought of plugin reading the remote theme's Gemspec and requiring any themes listed as dependencies there. I think the better path forward to be parent/child theme support in Jekyll core (for Gem-based themes), off which this plugin can build.
