### ISSUE TITLE
Theme could not be found

### ISSUE THREAD

**Issue by MFlisar** [benbalter/jekyll-remote-theme#39]
### Describe the bug

I can see that the theme is downloaded but afterwards the theme cant be found. I get following info when running `bundle exec jekyll serve` with `--verbose` flag:

    ...:/mnt/m/dev/homepage/mflisar.github.io$ bundle exec jekyll serve --verbose
		  Logging at level: debug
		Configuration file: /mnt/m/dev/homepage/mflisar.github.io/_config.yml
		  Logging at level: debug
			  Remote Theme: Using theme benbalter/retlab
			  Remote Theme: Downloading https://codeload.github.com/benbalter/retlab/zip/master to /tmp/jekyll-remote-theme-20181003-23851-jfp81i.zip
			  Remote Theme: Unzipping /tmp/jekyll-remote-theme-20181003-23851-jfp81i.zip to /tmp/jekyll-remote-theme-20181003-23851-xjr5zg
				 Requiring: github-pages
				 Requiring: jekyll-avatar
				 Requiring: jekyll-feed
				 Requiring: jekyll-github-metadata
		Dotenv not found. Skipping
				 Requiring: jekyll-seo-tag
			  GitHub Pages: github-pages v192
			  GitHub Pages: jekyll v3.7.4
		jekyll 3.7.4 | Error:  The retlab theme could not be found.
		/mnt/m/dev/homepage/mflisar.github.io/vendor/bundle/ruby/2.3.0/gems/jekyll-remote-theme-0.3.1/lib/jekyll-remote-theme/munger.rb:61:in `block in enqueue_theme_cleanup': unexpected return (LocalJumpError)

### Additional context

I'm using windows bash with bundle, not sure if this makes a difference? Any ideas why the downloaded theme can't be found?

**Comment by ellemenno** [comment]
I have run into the same problem: initial build with remote theme is successful, but auto-regeneration fails. Adding the `--trace` flag does not seem to reveal any additional info:

```
$ bundle exec jekyll build --trace --watch --source <project>/docs
Configuration file: <project>/docs/_config.yml
            Source: <project>/docs
       Destination: <project>/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
      Remote Theme: Using theme pixeldroid/programming-pages
                    done in 2.515 seconds.
 Auto-regeneration: enabled for '<project>/docs'

// make edits to index.md and save.. //

      Regenerating: 1 file(s) changed at 2018-11-15 20:39:44
                    index.md
      Remote Theme: Using theme pixeldroid/programming-pages
             Error: The programming-pages theme could not be found.
             Error: Run jekyll build --trace for more information.
```

Adding the `--verbose` flag gives a little bit more info:

```
$ bundle exec jekyll serve --source ./docs/ --verbose
  Logging at level: debug
Configuration file: ./docs/_config.yml
  Logging at level: debug
         Requiring: jemoji
         Requiring: jekyll-remote-theme
            Source: ./docs/
       Destination: ./_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
      Remote Theme: Using theme pixeldroid/programming-pages
      Remote Theme: Downloading https://codeload.github.com/pixeldroid/programming-pages/zip/master to /var/folders/fp/yvfwznrn0x91gzm5347f7h800000gn/T/jekyll-remote-theme-20181115-68512-16vcczr.zip
      Remote Theme: Unzipping /var/folders/fp/yvfwznrn0x91gzm5347f7h800000gn/T/jekyll-remote-theme-20181115-68512-16vcczr.zip to /private/var/folders/fp/yvfwznrn0x91gzm5347f7h800000gn/T/jekyll-remote-theme-20181115-68512-fakfks
         Requiring: github-pages

// reading, rendering, liquid, markup, etc. //

                    done in 2.843 seconds.
         Requiring: jekyll-watch
           Watcher: Ignoring (?-mix:_config\.yml)
 Auto-regeneration: enabled for './docs/'
[2018-11-15 20:53:32] INFO  WEBrick 1.4.2
[2018-11-15 20:53:32] INFO  ruby 2.5.1 (2018-03-29) [x86_64-darwin15]
[2018-11-15 20:53:32] DEBUG WEBrick::HTTPServlet::FileHandler is mounted on /.
[2018-11-15 20:53:32] DEBUG unmount .
[2018-11-15 20:53:32] DEBUG Jekyll::Commands::Serve::Servlet is mounted on .
    Server address: http://127.0.0.1:4000
[2018-11-15 20:53:32] INFO  WEBrick::HTTPServer#start: pid=68512 port=4000
  Server running... press ctrl-c to stop.

// edit index.md and save //

      Regenerating: 1 file(s) changed at 2018-11-15 20:53:57
                    index.md
      Remote Theme: Using theme pixeldroid/programming-pages
      GitHub Pages: github-pages v192
      GitHub Pages: jekyll v3.7.4
             Error: The programming-pages theme could not be found.
             Error: Run jekyll build --trace for more information.
```

**Comment by ellemenno** [comment]
_new data point_: the remote theme I want to us also provides a gem. I notice that if I install the theme gem (but keep using `remote-theme` in `_config.yml`), then `--watch` starts working for the remote theme.
