### ISSUE TITLE
Github Enterprise Support

### ISSUE THREAD

**Issue by chtitoon** [benbalter/jekyll-remote-theme#43]
Currently, all the themes can only be downloaded from [a public github](https://github.com/benbalter/jekyll-remote-theme/blob/master/lib/jekyll-remote-theme/downloader.rb#L6). It works great except in the case of enterprise GitHub...would it be possible to use the `github.hostname` provided by `jekyll-github-metadata` to resolve the `HOST` there?

**Comment by chtitoon** [comment]
Should this be addressed in some ways? Or I completely misunderstand the way the plugin works?

**Comment by mrmanc** [comment]
I’d love this to work with Enterprise. I’ve got around it by pushing themes to github.com though, and I’ve been fine with that as none of the themes are at all private/sensitive, so although I feel like things like this should work with Enterprise, I can’t supply a realistic use case for needing to push the theme to a private instance.
