### ISSUE TITLE
add support for version wildcards?

### ISSUE THREAD

**Issue by dmalan** [benbalter/jekyll-remote-theme#44]
### Is your feature request related to a problem? Please describe the problem you're trying to solve.

We have a theme for academic courses that we update minorly during a semester and majorly after a semester, and we'd like to lock courses to specific major releases, while still allowing them to get minor updates. (The courses' websites remain online after semester's ends as archives, so locking them to specific major releases ensures they don't accidentally get rebuilt and suddenly look like the newest semester.)

This is easy to do via a [gem](https://jekyllrb.com/docs/themes/#understanding-gem-based-themes) and `Gemfile`, but GitHub Pages does require that we make it available to teachers as a [remote theme](https://blog.github.com/2017-11-29-use-any-theme-with-github-pages/) instead.

While we can lock a website to a specific tag or branch, that's not quite as versatile as locking it to a specific major release (implemented as a GitHub tag).

### Describe the solution you'd like

No strong feelings, but perhaps the below, a la [Bundler](https://bundler.io/v1.5/gemfile.html)?

* `remote_theme: foo/bar, ~> 2.0.3`
* `remote_theme: foo/bar, ~> 2.1`
* `remote_theme: foo/bar, ~> 2.2.beta`

Or, perhaps more simply?

* `remote_theme: foo/bar@2.0.*`
* `remote_theme: foo/bar@2.*`
* `remote_theme: foo/bar@2.2.beta.*`

### Describe alternatives you've considered

We could version our theme as x.y.z, and then continually re-release "virtual" versions on GitHub, whereby we point x.y to the latest x.y.z and x to the latest x.y, but that feels a bit like reinventing this wheel!

### Additional context

Thank you for considering!

**Comment by benbalter** [comment]
Glad to review a pull request to implement this feature. I'd recommend following pesemistic versioning, rather than wild cards, which https://github.com/jlindsey/semantic may be able to help.

**Comment by dmalan** [comment]
Sure, thanks for the tip, made things much easier! PRed https://github.com/benbalter/jekyll-remote-theme/pull/45!

**Comment by dmalan** [comment]
@benbalter, at the bot's prompting, just wanted to follow up on your thoughts on https://github.com/benbalter/jekyll-remote-theme/pull/45?

**Comment by dmalan** [comment]
Just wanted to re-ping, @benbalter, to keep the bot at bay!

**Comment by dmalan** [comment]
Hi @benbalter, just hoping to keep this one alive!

**Comment by dmalan** [comment]
Hi @benbalter, just pinging, per the bot!

**Comment by dmalan** [comment]
Hi @benbalter, just keeping this one open.

**Comment by dmalan** [comment]
Just keeping alive!
