### ISSUE TITLE
Support specifying a URL for the remote theme

### ISSUE THREAD

**Issue by TheLocehiliosan** [benbalter/jekyll-remote-theme#50]
### Is your feature request related to a problem? Please describe the problem you're trying to solve.

I would like to speed up my development builds. Every time I start jekyll, the remote theme must re-download.

### Describe the solution you'd like

In addition to User/Repo@Ref, I think it would be nice to support a URL (http/https/file). Being able to specify a local URL (possibly a `file://` protocol) would make the start-up quick.

### Describe alternatives you've considered

There exist PRs (which have been closed by the bot 😕) which add caching options. This seems like it might help, but I want to be able to have the zip of theme local, and have it use that local file the first time. This would be more useful to me, as I do all of my jekyll building inside of Docker containers, and often I'm working in a new container.

**Comment by datapolitical** [comment]
I'd like to re-up this. I'm working on a site and using a remote theme I'm updating, and I'd like to figure out the right way to manage development of it with my site assets. referencing a local remote theme seems like the obvious choice.
