### ISSUE TITLE
New release to support jekyll 4.0.0?

### ISSUE THREAD

**Issue by pmpinto** [benbalter/jekyll-remote-theme#58]
I see that gemspec was already updated 1 month ago: https://github.com/benbalter/jekyll-remote-theme/blob/master/jekyll-remote-theme.gemspec#L19

But the latest release is still requiring `jekyll ~> 3.5`.
Any plans for a future release?

**Comment by pmpinto** [comment]
Meanwhile, if it helps anyone else, you can point to a gem that's hosted on GitHub like this:
```
gem "jekyll-remote-theme", github: "benbalter/jekyll-remote-theme", branch: "master"
```

**Comment by benbalter** [comment]
Started on this in https://github.com/benbalter/jekyll-remote-theme/pull/61 but blocked by https://github.com/jekyll/jekyll-sass-converter/issues/95.
