### ISSUE TITLE
Error when remote theme doesn't have _sass folder

### ISSUE THREAD

**Issue by parkr** [benbalter/jekyll-remote-theme#59]
### Describe the bug

When a remote theme doesn't have a `_sass` directory, the remote theme downloader throws a 404 error.

### Steps to reproduce the behavior

Create a new site with a `_config.yml` with `remote_theme: scotte/jekyll-clean`. Create a page, and run `jekyll build`.

### Expected behavior

I'd expect the site to build, just without looking in the theme directory for Sass.

### Screenshots

No screenshots, but the error I see is:

```text
Invalid theme folder: _sass
      Remote Theme: Using theme scotte/jekyll-clean
             Fatal: Jekyll::RemoteTheme::DownloadError
                    404 - Not Found
```

<details>
<summary>Backtrace</summary>

```
/hoosegow/.bundle/ruby/2.5.0/gems/jekyll-remote-theme-0.4.0/lib/jekyll-remote-theme/downloader.rb:67:in `raise_unless_sucess'
/hoosegow/.bundle/ruby/2.5.0/gems/jekyll-remote-theme-0.4.0/lib/jekyll-remote-theme/downloader.rb:44:in `block (2 levels) in download'
/usr/share/rbenv/versions/2.5.3/lib/ruby/2.5.0/net/http.rb:1503:in `block in transport_request'
/usr/share/rbenv/versions/2.5.3/lib/ruby/2.5.0/net/http/response.rb:165:in `reading_body'
/usr/share/rbenv/versions/2.5.3/lib/ruby/2.5.0/net/http.rb:1502:in `transport_request'
/usr/share/rbenv/versions/2.5.3/lib/ruby/2.5.0/net/http.rb:1464:in `request'
/hoosegow/.bundle/ruby/2.5.0/gems/jekyll-remote-theme-0.4.0/lib/jekyll-remote-theme/downloader.rb:43:in `block in download'
/usr/share/rbenv/versions/2.5.3/lib/ruby/2.5.0/net/http.rb:910:in `start'
/usr/share/rbenv/versions/2.5.3/lib/ruby/2.5.0/net/http.rb:609:in `start'
/hoosegow/.bundle/ruby/2.5.0/gems/jekyll-remote-theme-0.4.0/lib/jekyll-remote-theme/downloader.rb:42:in `download'
/hoosegow/.bundle/ruby/2.5.0/gems/jekyll-remote-theme-0.4.0/lib/jekyll-remote-theme/downloader.rb:24:in `run'
/hoosegow/.bundle/ruby/2.5.0/gems/jekyll-remote-theme-0.4.0/lib/jekyll-remote-theme/munger.rb:25:in `munge!'
/hoosegow/.bundle/ruby/2.5.0/gems/jekyll-remote-theme-0.4.0/lib/jekyll-remote-theme.rb:27:in `init'
/hoosegow/.bundle/ruby/2.5.0/gems/jekyll-remote-theme-0.4.0/lib/jekyll-remote-theme.rb:33:in `block in <top (required)>'
/hoosegow/.bundle/ruby/2.5.0/gems/jekyll-3.8.5/lib/jekyll/hooks.rb:103:in `block in trigger'
/hoosegow/.bundle/ruby/2.5.0/gems/jekyll-3.8.5/lib/jekyll/hooks.rb:102:in `each'
/hoosegow/.bundle/ruby/2.5.0/gems/jekyll-3.8.5/lib/jekyll/hooks.rb:102:in `trigger'
/hoosegow/.bundle/ruby/2.5.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:105:in `reset'
/hoosegow/.bundle/ruby/2.5.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:31:in `initialize'
```

</details>

**Comment by benbalter** [comment]
@parkr I don't believe the issue has to do with the `_sass` folder, but with the fact that the repo doesn't have a `master` branch and no other branch is specified.

`remote_theme: scotte/jekyll-clean@gh-pages` builds for me sucessfully.

**Comment by parkr** [comment]
Thank you so much!! That clears things up.

What do you think about hitting the GitHub API to fetch the default branch and pulling that `.zip` file instead of using `master`?

**Comment by benbalter** [comment]
> What do you think about hitting the GitHub API to fetch the default branch and pulling that `.zip` file instead of using `master`?

Not sure if it's worth the complexity? The plugin would then be subject to API limits so after a certain number of builds it would just stop building.

**Comment by parkr** [comment]
Ok! Maybe a quick update to the error message to say it couldn’t find a theme on the master branch?
