### ISSUE TITLE
Pages are not included from the remote theme

### ISSUE THREAD

**Issue by aksakalli** [benbalter/jekyll-remote-theme#64]
This might not be a bug but I couldn't figure out how to include some pages from remote theme.

https://github.com/aksakalli/jekyll-doc-theme/issues/37

### Steps to reproduce the behavior

1. Use `remote_theme: aksakalli/jekyll-doc-theme@gh-pages`
2. Some pages like `allposts.html` are not included from the remote theme.

How can I include such default remote theme pages?

**Comment by kenjdavidson** [comment]
Fairly certain this is working as designed.  Custom theme files can be placed in:

    assets/allposts.html

with the front matter 

    ---
    permalink: allposts.html
    ---

which results in the

     _site/allposts.html

file being generated.
