### ISSUE TITLE
Pleas release 0.4.2 with #62

### ISSUE THREAD

**Issue by damageboy** [benbalter/jekyll-remote-theme#70]
### Is your feature request related to a problem? Please describe the problem you're trying to solve.

Related to #61 
The released version crashes when calling `configure_sass`

### Describe the solution you'd like

Please release 0.4.2 with latest master

### Describe alternatives you've considered

I'm currently hot patching with `sed -i`

**Comment by damageboy** [comment]
Is there anything I could do to help facilitate a 0.4.2/

**Comment by benbalter** [comment]
https://github.com/benbalter/jekyll-remote-theme/releases/tag/v0.4.2
