### ISSUE TITLE
Allow for custom theme structure

### ISSUE THREAD

**Issue by malimach** [benbalter/jekyll-remote-theme#79]
The plugin does not respect non-default values for some settings, most notably:
```
layouts_dir
```
```
includes_dir
```
```
sass_dir
```

**Comment by deb-master** [comment]
Related: #49

**Comment by deb-master** [comment]
[Also related](https://github.community/t/css-for-gh-pages-project-site-using-remote-theme-not-built-installed/10384/4)

I think that ideally there would be support for these settings on the *theme side* (using a theme-specific `_config.yml` [like in gem themes](https://jekyllrb.com/docs/themes/#pre-configuring-theme-gems40)).
