### ISSUE TITLE
Testing feedback

### ISSUE THREAD

**Issue by daviddarnes** [benbalter/jekyll-remote-theme#8]
Hi 👋, I created the theme [Alembic](https://github.com/daviddarnes/alembic). I was [copied in on a thread](https://talk.jekyllrb.com/t/plugin-jekyll-remote-theme/1089) from @DirtyF to test out this plugin. Here's what I found:

## Installation
1. Created a new site using `jekyll new`
2. Followed the installation steps of this plugin (added the plugin to the `jekyll_plugins` group in the `Gemfile`)
3. Tried serving the site with `bundle exec jekyll serve`, but due to my theme using [jekyll-seo-tag](https://github.com/jekyll/jekyll-seo-tag) the site failed to build. I've hit problems before with the specific `{% seo %}` so maybe this is more of an issue with that gem? It would be nice if it caused a warning instead?
4. Added the jekyll-seo-tag plugin and tried again and it worked as expected 🎉

## Parting notes
- Works exactly as expected 👍
- Issue with theme dependancies, but [as seen here](https://github.com/benbalter/jekyll-remote-theme/pull/1#issuecomment-338243958) there are problems with catering for this
- Should plugins error more gracefully? Open question 💬
- The resulting site is quite blank, maybe my theme isn't working hard enough 😳

Discussion thread on the Jekyll forums if people want to chat further https://talk.jekyllrb.com/t/plugin-jekyll-remote-theme/1089/5

**Comment by benbalter** [comment]
@daviddarnes thanks for this great feedback. As an initial release, plugins are a bit of a rough edge still. Although https://github.com/benbalter/jekyll-remote-theme/issues/4 is just a placeholder for the moment, I'd love to see a better user experience around plugins. At the very least, we could potentially warn users if the theme requires a plugin that's not in the config, and ideally, we'd be able to require it if it's part of the whitelist (or always require it if not in safe mode).

**Comment by daviddarnes** [comment]
@benbalter you're very welcome! Totally understand with plugins, I appreciate that you need to take a somewhat delicate approach to this as it could potentially affect a lot of people. If you require any more testing just let us know, I'll probably be dropping by this repo every so often anyway. I'm keen to make my theme versatile for different platforms.
