### ISSUE TITLE
Newly created repositories now have default branch `main`: `OWNER/REPOSITORY` gives not found error

### ISSUE THREAD

**Issue by trasparente** [benbalter/jekyll-remote-theme#84]
### Is your feature request related to a problem? Please describe the problem you're trying to solve.

Since October 1 2020 we need to create a `master` branch or rename the `main` one.

### Describe the solution you'd like

If theme repository has no `master` branch, `main` could be searched.

### Describe alternatives you've considered

We will forever need `OWNER/REPOSITORY@main`

### Additional context

This is a wonderful gem :heart:

**Comment by daviddarnes** [comment]
Wonder if this line could be extended to cater `main` default branch names:
https://github.com/benbalter/jekyll-remote-theme/blob/a3c6bc44652ccefee90abe05e3a3810b64f71cf3/lib/jekyll-remote-theme/theme.rb#L54

`master` is hard coded here so I don't see why `main` couldn't be as well? Main is going to become very popular with repos from now on

**Comment by seshrs** [comment]
@daviddarnes Unfortunately it looks like it won't be that simple. To know that we should default to `main` and not `master`, we'd have to check if the Git ref for `master` does not exist. We may run into similar concerns expressed in #45...

**Comment by daviddarnes** [comment]
@seshrs ah I see! I didn't think of that
