### ISSUE TITLE
Not all theme folders copied

### ISSUE THREAD

**Issue by datapolitical** [benbalter/jekyll-remote-theme#88]
### Describe the bug
My Jekyll theme has additional features to display recipes, which require files in a "recipes" folder. That folder is not copied by the plugin.

### Steps to reproduce the behavior

Run the plugin on [datapolitical/contrast](https://www.github.com/datapolitical/contrast)

### Expected behavior

All theme files are copied.

### Additional Comments

I'm happy to fork the plugin to add this functionality but I don't understand how because I haven't seen a plugin divided into a lib and spec folder before and I'm not sure what to edit.

**Comment by parkr** [comment]
@datapolitical Themes can only provide `_layouts`, `_includes`, `_sass`, and `assets` directories to the site that's using it. This is a product decision on Jekyll's end.
