### ISSUE TITLE
Ship v0.4.3

### ISSUE THREAD

**Issue by parkr** [benbalter/jekyll-remote-theme#90]
Let's ship a v0.4.3. /cc @benbalter 

- Fix for fetching non-master branch (i.e. using "HEAD") - #87
- Added extra context to error message when remote theme download fails #85
- Require kramdown-parser-gfm to fix travis #86
 
I'd consider the s/master/HEAD/g change to the a bug fix but we could go to v0.5.0 if you'd prefer.

**Comment by benbalter** [comment]
https://github.com/benbalter/jekyll-remote-theme/releases/tag/v0.4.3

**Comment by parkr** [comment]
Thank you! 😄
